"""Add Spell Model, character_spell Association Table

Revision ID: 642276a295ac
Revises: 602846452235
Create Date: 2023-06-27 15:36:08.867523

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '642276a295ac'
down_revision = '602846452235'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spells',
    sa.Column('spell_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('range', sa.String(), nullable=True),
    sa.Column('casting_time', sa.String(), nullable=True),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('higher_level', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('spell_id')
    )
    op.create_table('character_spell',
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('spell_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.character_id'], name=op.f('fk_character_spell_character_id_characters')),
    sa.ForeignKeyConstraint(['spell_id'], ['users.user_id'], name=op.f('fk_character_spell_spell_id_users'))
    )
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_characters_owner_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_characters_owner_users'), 'users', ['owner'], ['user_id'])
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_characters_owner_users'), type_='foreignkey')
        batch_op.create_foreign_key('fk_characters_owner_id_users', 'users', ['owner_id'], ['user_id'])
        batch_op.drop_column('owner')

    op.drop_table('character_spell')
    op.drop_table('spells')
    # ### end Alembic commands ###
