"""Add Campaign  Model

Revision ID: bb4eca738349
Revises: c7cbbdccd14e
Create Date: 2023-06-29 13:10:39.915325

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb4eca738349'
down_revision = 'c7cbbdccd14e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('dm', sa.Integer(), nullable=True),
    sa.Column('group_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['dm'], ['dungeonmasters.dm_id'], name=op.f('fk_campaigns_dm_dungeonmasters')),
    sa.PrimaryKeyConstraint('campaign_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('campaigns')
    # ### end Alembic commands ###
