"""Add Dungeon_master Model

Revision ID: c7cbbdccd14e
Revises: 642276a295ac
Create Date: 2023-06-29 12:13:49.626632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7cbbdccd14e'
down_revision = '642276a295ac'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dungeonmasters',
    sa.Column('dm_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('dm_id')
    )
    with op.batch_alter_table('character_spell', schema=None) as batch_op:
        batch_op.drop_constraint('fk_character_spell_spell_id_users', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_character_spell_spell_id_spells'), 'spells', ['spell_id'], ['spell_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_spell', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_character_spell_spell_id_spells'), type_='foreignkey')
        batch_op.create_foreign_key('fk_character_spell_spell_id_users', 'users', ['spell_id'], ['user_id'])

    op.drop_table('dungeonmasters')
    # ### end Alembic commands ###
